# Generated by Django 3.0.2 on 2020-02-08 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_1', '0003_auto_20200208_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only characters are allowed.')], verbose_name='last name'),
        ),
    ]
